# Generated by Django 2.1.2 on 2018-10-20 23:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affiliates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('originator', models.CharField(blank=True, max_length=200)),
                ('industry', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('minimum_investment', models.IntegerField()),
                ('annual_interest', models.IntegerField()),
                ('percent_funded', models.IntegerField(default=0)),
                ('current_funded', models.IntegerField(default=0)),
                ('offering_size', models.IntegerField(blank=True)),
                ('term', models.IntegerField(blank=True)),
                ('photo_main', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_published', models.BooleanField(default=True)),
                ('is_open', models.BooleanField(default=True)),
                ('offer_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('affiliate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='affiliates.Affiliate')),
            ],
        ),
    ]
